### ISSUE TITLE
Add isNearSingular method

### ISSUE THREAD

**Issue by shaun-edwards** [shaun-edwards/moveit_simple#11]
A method is needed that returns true when the robot arm configuration is near singular.

**Comment by nsnitish** [comment]
@shaun-edwards! Determinant of the [Jacobian](http://docs.ros.org/jade/api/moveit_core/html/classmoveit_1_1core_1_1RobotState.html#af14fd5a53bf052f12eeb81237dbdc67b) is what we are concerned here, right?

**Comment by shaun-edwards** [comment]
Yes...although @geoffreychiou expressed some reservation about using the jacobian to determine singularity.

**Comment by nsnitish** [comment]
@geoffreychiou Can you please elaborate?

**Comment by geoffreychiou** [comment]
Basically a singularity occurs when the determinant of the Jacobian is equal to zero, but I found a article/stackoverflow  comment a while back saying that you can't just take the determinant of J and check if it is close to zero.

One possibility is to compare the joint velocities to the Cartesian velocity. When the robot is near a singularity, the joint velocities should be very large compared to the Cartesian velocity. It would be up to you to determine what the threshold should be.
