### ISSUE TITLE
Moving in with moveit?

### ISSUE THREAD

**Issue by v4hn** [shaun-edwards/moveit_simple#2]
Hey @shaun-edwards,

You just pointed at this package from ros-answers, so I had a look.

It is a great idea to create a ``small brother'' of the move_group node, that can be instantiated/controlled in a C++ context without ROS interaction!
The MoveGroup action outgrew the simple industrial use-case quite some time ago and this would remove complexity for some applications quite a lot.

What do you think about integrating this into the MoveIt repository in kinetic?
That would probably give it a bit more users and because we bump sonames in every release of kinetic, you don't have to consider ABI breakage. :)
I do understand that quite a bit of intended functionality is missing here at the moment.

**Comment by shaun-edwards** [comment]
@v4hn, I'm honored by your request.  I've approach @davetcoleman about this as well.  He's given me some great feedback, [here](https://github.com/davetcoleman/moveit_simple/pull/1).  

I've got some work to do before it's minimally functional.  My plan is to submit it for inclusion in MoveIt once that's done.  I am interested to get feedback as I develop, so it doesn't seem like I'm pushing it into MoveIt as take it or leave it.

**Comment by v4hn** [comment]
I see, glad to hear this is being discussed. :)
I hope you find the time to incorporate the feedback and let's see how the module moves on.
Personally I would prefer to see such a project integrated early and continue developing from there - clearly not just move it over as ``take it or leave it''. But that's your choice, and I don't know what the other devs think about that. :)

Feel free to ping me if you need more feedback (although apparently you have plenty :) )

I'll close this issue for now.

**Comment by 130s** [comment]
+1 for the idea.
I think we can keep this open for better visibility (I didn't notice until I used search feature onGitHub issue view).
