### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by james2254** [shaun-edwards/moveit_simple#24]
robot_state_’ was not declared in this scope.
**/home/james/catkin_ws/src/moveit_simple-indigo-devel/moveit_simple/src/moveit_simple.cpp: In member function ‘bool moveit_simple::Robot::isNearSingular(const std::vector<double>&) const’:
/home/james/catkin_ws/src/moveit_simple-indigo-devel/moveit_simple/src/moveit_simple.cpp:802:5: error: ‘robot_state_’ was not declared in this scope
     robot_state_->copyJointGroupPositions(joint_group_->getName(), local_joint_point);
     ^
/home/james/catkin_ws/src/moveit_simple-indigo-devel/moveit_simple/src/moveit_simple.cpp:804:3: error: ‘robot_state_’ was not declared in this scope
   robot_state_->setJointGroupPositions(joint_group_, local_joint_point);
   ^
make[2]: *** [moveit_simple-indigo-devel/moveit_simple/CMakeFiles/moveit_simple.dir/src/moveit_simple.cpp.o] 错误 1
make[1]: *** [moveit_simple-indigo-devel/moveit_simple/CMakeFiles/moveit_simple.dir/all] 错误 2
make: *** [all] 错误 2
Invoking "make -j4 -l4" failed
**

**Comment by shaun-edwards** [comment]
Thanks for pointing this out.  It looks like this broke after the PR from @nsnitish.  CI also has the same error: https://travis-ci.org/shaun-edwards/moveit_simple/jobs/269031867

I will look into this, but if you can suggest a fix, that would be great.

**Comment by nsnitish** [comment]
This issue arises due to two PRs( #21 and #23 ) which are actually based on different original branches. It was [meant to be modified](https://github.com/shaun-edwards/moveit_simple/pull/23/files#diff-8ae580aedd7e6266898c159ae2e4a380R790). I have filed PR #25 which takes care of this.

**Comment by shaun-edwards** [comment]
This has been resolved by #25.  Please re-open if this is not the case.
