### ISSUE TITLE
Reason for using plusone fork of rosparam_handler?

### ISSUE THREAD

**Issue by gavanderhoorn** [shaun-edwards/moveit_simple#31]
Afaict all changes added in https://github.com/plusone-robotics/rosparam_handler/commit/5e511fb95b2d3dac163aec91c9925068dc55e628 are already (?) present upstream.

**Comment by gavanderhoorn** [comment]
Using upstream would allow for removing the source dep from the `.rosinstall` file (with similar benefits as #32).

**Comment by shaun-edwards** [comment]
When i forked it, there wasnt a debian.  Im not sure if there is one now. As a rule PlusOne will fork any project that may not be stable. This ensures we aren't tracking down problems due to changes upstream. As we move towards a ROS release, these upstream dependencies will need to be addressed.

**Comment by gavanderhoorn** [comment]
@shaun-edwards wrote:
> When i forked it, there wasnt a debian. Im not sure if there is one now.

There are.

> As a rule PlusOne will fork any project that may not be stable. This ensures we aren't tracking down problems due to changes upstream.

An alternative might be to use a `.rosinstall` file with a specific commit as `version` instead of `master` or some other default branch. That way you don't need to fork and are still using a specific version.
