### ISSUE TITLE
Provide prettyprint header(s) as part of moveit_simple

### ISSUE THREAD

**Issue by gavanderhoorn** [shaun-edwards/moveit_simple#32]
It's really just a single header, and seeing as `prettyprint` is not released on any platform (haven't checked extensively) targeted by ROS Indigo/Kinetic, it almost unnecessarily complicates building `moveit_simple`.

It also makes it impossible to release `moveit_simple` through the ROS buildfarm.

**Comment by gavanderhoorn** [comment]
Also just noticed that `prettyprint` is only a build depend, so that makes this even more feasible.

**Comment by shaun-edwards** [comment]
Agreed. Will need to fix before a ROS release.
