### ISSUE TITLE
Break up moveit simple into offline robot and online robot object.

### ISSUE THREAD

**Issue by shaun-edwards** [shaun-edwards/moveit_simple#4]
The `moveit_simple` object is currently used in two different manors.  The first way uses `moveit_simple` to perform kinematics and path planning.  The second way builds on top of this functionality to execute paths (online).  Specifically the [execute method](https://github.com/shaun-edwards/moveit_simple/blob/indigo-devel/moveit_simple/include/moveit_simple/moveit_simple.h#L150) and the [updateState](https://github.com/shaun-edwards/moveit_simple/blob/indigo-devel/moveit_simple/include/moveit_simple/moveit_simple.h#L198) are used exclusively for online functionality.  The big difference between offline and online functionality is that the current robot state (online) is often used to seed various IK calls.  When used in an offline manor, how the seed is determines is unclear (in reality it simply uses the joint pose calculated from the last call to IK, which might not be expected).

**Comment by shaun-edwards** [comment]
@geoffreychiou, could you look at this one?

**Comment by nsnitish** [comment]
I think we have already addressed this in #21
