### ISSUE TITLE
Use binary version of rosparam_handler

### ISSUE THREAD

**Issue by 130s** [shaun-edwards/moveit_simple#43]
Just FYI that the new release is made https://github.com/cbandera/rosparam_handler/issues/38 that looks like includes a lot of changes since the last release.

**Comment by MauleshSTrivedi** [comment]
good catch.

**Comment by geoffreychiou** [comment]
They patched the CI bug we were getting in the 0.1.3 release. The current release on apt is 0.1.2 according to [this](http://packages.ros.org/ros/ubuntu/dists/xenial/main/binary-amd64/Packages). I'll remove it from the rosinstall file as soon as they update it.
