### ISSUE TITLE
Build Breaking

### ISSUE THREAD

**Issue by geoffreychiou** [shaun-edwards/moveit_simple#44]
moveit_simple is no longer building on kinetic after latest ros-kinetic-desktop upgrade:

This has previously been building as part of a larger kinetic project on CI. I re-ran a build that had previously passed in CI and it failed in the exact same location.

Build Error:
```
In file included from /temp_ws/src/moveit_simple/moveit_simple/include/moveit_simple/moveit_simple.h:46:0, from 
/temp_ws/src/moveit_simple/moveit_simple/src/moveit_simple.cpp:19:
/temp_ws/devel/.private/moveit_simple/include/moveit_simple/moveit_simple_dynamic_reconfigure_Parameters.h:13:42: fatal error: rosparam_handler/utilities.hpp: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/moveit_simple.dir/src/moveit_simple.cpp.o] Error 1
make[1]: *** [CMakeFiles/moveit_simple.dir/all] Error 2
make: *** [all] Error 2
```
Things I have tried:
- Reboot and clean build
- Building rosparam_handler from source
- Building with plusone-robotics/rosparam_handler from source
- Building with dynamic_reconfigure from source

@shaun-edwards any other ideas?

**Comment by geoffreychiou** [comment]
Looks like I didn't clean before cloning rosparam_handler from source...

**Comment by geoffreychiou** [comment]
Looks like it is still breaking in CI, per @shaun-edwards request, I removed rosparam_handler from the .rosinstall and tried to build using the version on apt [here](https://travis-ci.org/geoffreychiou/moveit_simple/jobs/346375359): 

```
Errors     << moveit_simple:make /root/catkin_ws/logs/moveit_simple/build.make.000.log
In file included from /root/catkin_ws/src/moveit_simple/moveit_simple/include/moveit_simple/moveit_simple.h:46:0,
                 from /root/catkin_ws/src/moveit_simple/moveit_simple/src/moveit_simple.cpp:19:
/root/catkin_ws/devel/.private/moveit_simple/include/moveit_simple/moveit_simple_dynamic_reconfigure_Parameters.h:13:42: fatal error: rosparam_handler/utilities.hpp: No such file or directory
 #include <rosparam_handler/utilities.hpp>
                                          ^
compilation terminated.
make[2]: *** [CMakeFiles/moveit_simple.dir/src/moveit_simple.cpp.o] Error 1
make[1]: *** [CMakeFiles/moveit_simple.dir/all] Error 2
make: *** [all] Error 2
cd /root/catkin_ws/build/moveit_simple; catkin build --get-env moveit_simple | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```

**Comment by geoffreychiou** [comment]
Build passes in CI [here](https://travis-ci.org/geoffreychiou/moveit_simple/jobs/346381445) when I point to my fork [here](https://github.com/geoffreychiou/rosparam_handler/tree/gc_fix_ci).

Only change to rosparam_handler is adding a / to the end of include/rosparam_handler:

```
install(
        DIRECTORY include/rosparam_handler/
        DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
)
```

**Comment by geoffreychiou** [comment]
See #45.

**Comment by 130s** [comment]
FYI `rosparam_handler` with fixes that bugged us is now binary-released. https://github.com/cbandera/rosparam_handler/pull/46#issuecomment-376598328
