### ISSUE TITLE
moveit_simple_msgs package is missing install rule

### ISSUE THREAD

**Issue by 130s** [shaun-edwards/moveit_simple#76]
@geoffreychiou found it.

Not sure yet though, why on CI for PRs passed (e.g. [this](https://travis-ci.org/plusone-robotics/moveit_simple/builds/493951741#L666) for https://github.com/plusone-robotics/moveit_simple/pull/75) without install rules as industrial_ci by default uses only install space.

**Comment by geoffreychiou** [comment]
I actually don't see CI running anymore on github, did it get removed?

**Comment by 130s** [comment]
I do see CI ran for the last several MRs.  
![screenshot from 2019-02-18 15-30-06](https://user-images.githubusercontent.com/1840401/52981057-2b86b100-3392-11e9-8e36-078984639f28.png)


Where are you looking at @geoffreychiou?

**Comment by geoffreychiou** [comment]
Nevermind, github must have changed the UI, it used to say "All checks passed" with a green icon in the the PR.

**Comment by 130s** [comment]
I didn't know this! Good learning. http://docs.ros.org/kinetic/api/catkin/html/howto/format2/building_msgs.html
> Since catkin installs message, service and action targets automatically, no extra install() commands are needed for them.
