### ISSUE TITLE
Motion timing (%speed) should be a dynamic reconfigure parameter

### ISSUE THREAD

**Issue by shaun-edwards** [shaun-edwards/moveit_simple#8]
It would be convenient if `moveit_simple` had a speed "knob" that could be used to speed up or slow down motion timing (from the nominal).

**Comment by shaun-edwards** [comment]
@geoffreychiou, could you take a look at this.

**Comment by shaun-edwards** [comment]
@MauleshSTrivedi, here's another one that you can look at if you are waiting on me.  @geoffreychiou started a PR a while back, but it's really out of date.  Have look.  You can try to update the PR or start a new one (you choice).

**Comment by MauleshSTrivedi** [comment]
@shaun-edwards I will have a loot at it.
